.386
CODE SEGMENT USE16
ASSUME CS:CODE
START:
    XOR AX,AX
    MOV DS,AX
    XOR AX,AX
    XOR BX,BX
    XOR CX,CX
    XOR DX,DX
    MOV AX,DS:[1H*4]
    MOV BX,DS:[1H*4+2]
    MOV CX,DS:[13H*4]
    MOV DX,DS:[13H*4+2]
    MOV AH,4CH
    INT 21H
CODE ENDS
    END START