.386

DATA SEGMENT USE16
DATA ENDS

CODE SEGMENT USE16
ASSUME CS:CODE,DS:DATA,SS:STACK

OLD_INT DW ?,?
NEW16H:
        CMP AH,00H
        JE UTu
        CMP AH,10H
        JE UTu
        JMP DWORD PTR OLD_INT
UTu:
    PUSHF
    CALL DWORD PTR OLD_INT
    CMP AL,41H
    JB NOTCHANGE
    CMP AL,5AH
    JA NOTCHANGE
CHANGE:
    ADD AL,20H
NOTCHANGE:
    IRET

START:
    XOR AX,AX
    MOV DS,AX
    MOV AX,DS:[16H*4]
    MOV OLD_INT,AX
    MOV AX,DS:[16H*4+2]
    MOV OLD_INT+2,AX
    CLI
    MOV WORD PTR DS:[16H*4],OFFSET NEW16H
    MOV DS:[16H*4+2],CS
    STI
    MOV DX,OFFSET START+15
    SHR DX,4
    ADD DX,10H
    MOV AL,0
    MOV AH,31H
    INT 21H
CODE ENDS
STACK SEGMENT USE16 STACK
    DB 200 DUP(0)
STACK ENDS
    END START
    