.386
STACK SEGMENT USE16 STACK
	DB 200 DUP(0);分配栈空间
STACK ENDS

DATA SEGMENT USE16;数据段定义变量
BUF1 DB 0,1,2,3,4,5,6,7,8,9
BUF2 DB 10 DUP(0)
BUF3 DB 10 DUP(0)
BUF4 DB 10 DUP(0)

DATA ENDS
CODE SEGMENT USE16
ASSUME CS:CODE,DS:DATA,SS:STACK
START:
	MOV AX,DATA;将data段首地址送到DS中
	MOV DS, AX
	MOV SI,0
	MOV CX,10;计数器
LOOPA:;与JNE LOOPA一起控制循环,每循环一次，计数器加一，直到cx==10；
	MOV AL,BUF1[SI]
	MOV BUF2[SI],AL;从BUF1取一个数送到BUF2
	INC AL;AL自增1
	MOV BUF3[SI],AL;从BUF1取下数送到BUF3
	ADD AL,3;AL自增3
	MOV BUF4[SI],AL;从BUF1取数送到BUF4
	INC SI;Si自增
	DEC CX;cx自减，控制循环次数
	JNE LOOPA;控制循环
	MOV AH,4CH;结束程序
	INT 21H;
CODE ENDS
END START