.386
STACK SEGMENT USE16 STACK
DB 200 DUP(0)
STACK ENDS

DATA SEGMENT USE16
OUTPUT_MSG1 DB 0AH,'welcome to----','$'
OUTPUT_MSG2 DB 0AH,0AH,'please enter your name : ','$'
OUTPUT_MSG3 DB 0AH,'please enter you password : ' ,'$'
OUTPUT_MSG4 DB 0AH,'please enter the goods name : ' ,'$'
OUTPUT_MSG5 DB 0AH,'fail find!',0AH,'$'
OUTPUT_MSG6 DB 0AH,'success find! ',0AH ,'$'
OUTPUT_MSG7 DB 0AH,'Level: ','$'
ERROR_MSG_N DB 0AH,'name wrong! please enter again!','$'
ERROR_MSG_P DB 0AH,'password wrong!please enter again!','$'
REGISTER_SUCCESS DB 0AH,'register success!',0AH,'$'
BOSS_NAME  DB  'ZHUZHICHENG';姓名（必须是自己名字的拼音）
BOSS_NAME_LENGTH EQU $-BOSS_NAME;字符串长度
PASSWORD   DB  '123456';密码
PASSWORD_LENGTH EQU $-PASSWORD;字符串长度
SHOP_NAME  DB  'MY----SHOP----0.0','$';网店名称

IN_NAME	    DB  60  ;用户键入姓名
			DB  ?
			DB  60 DUP('$')
IN_PWD      DB	60	;用户键入密码
			DB  ?
			DB  60 DUP('$')
GOODS_NAME	DB	10	;用户键入商品名称
			DB  ?
			DB  10 DUP(0)
N    EQU   30
AUTH   DB 0

RP DW ?   ;实际销售价格
SCORE DD ?  ;推荐度
IMUL1 DD 1280D
IMUL2 DD 64D

GA1  DB    'PEN',7 DUP(0),10;商品名称及折扣
	DW  35,56,70,25,?;推荐度还未计算
GA2  DB    'BOOK',6 DUP(0) ,9; 商品名称及折扣
	DW  12,30,25,5,?;推荐度还未计算
GAN  DB 	N-2 DUP( 'Temp-Value',8,15,0,20,0,30,0,2,0,?,?) ;除了2个已经具体定义了的商品信息以外，其他商品信息暂时假定为一样的。
DATA ENDS

CODE SEGMENT USE16
ASSUME CS:CODE,DS:DATA,SS:STACK
START:
	MOV AX,DATA
	MOV DS,AX
	LEA DX,OUTPUT_MSG1;输出店名信息提示
	MOV AH,09H
	INT 21H
	MOV DX,OFFSET SHOP_NAME;店名
	MOV AH,9
	INT 21H
L1:
	LEA DX,OUTPUT_MSG2;输入姓名提示
	MOV AH,9
	INT 21H
	LEA DX,IN_NAME;读入姓名
	MOV AH,0AH
	INT 21H
	CMP 2[IN_NAME],0DH;判断是否为回车
	JE INDEX1
	CMP 1[IN_NAME],1;判断是否只有一个字符
	JNE L1_YES;不止一个字符
	CMP 2[IN_NAME],'q';只有一个字符为q
	JE EXIT;退出程序	
	JMP L1_YES;只有一个字符不为q	
	L1_YES:;输入密码
		LEA DX,OUTPUT_MSG3;输入密码提示
		MOV AH,9
		INT 21H
		LEA DX,IN_PWD;读入密码
		MOV AH,0AH
		INT 21H
		JMP CMP_NAME;验证名字
L2:
	CMP_NAME:
		CMP 1[IN_NAME],BOSS_NAME_LENGTH;先判断姓名长度是否相等
		JNE ERROR_NAME

		MOV CX,0
		LEA SI,IN_NAME+2
		LEA DI,BOSS_NAME
		LOOPA:
			MOV AL,[SI]
			MOV BL,[DI]
			CMP AL,BL
			JNE ERROR_NAME
			INC CX
			INC SI
			INC DI
			CMP CX,BOSS_NAME_LENGTH
			JNE LOOPA
		JMP CMP_PWD			
	CMP_PWD:
		CMP 1[IN_PWD],PASSWORD_LENGTH;先判断密码长度是否相等
		JNE ERROR_PWD
		MOV CX,0
		LEA SI,IN_PWD+2
		LEA DI,PASSWORD
		LOOPB:
			MOV AL,[SI]
			MOV BL,[DI]
			CMP AL,BL
			JNE ERROR_PWD
			INC CX
			INC SI
			INC DI
			CMP CX,PASSWORD_LENGTH
			JNE LOOPB
		MOV AUTH,1
		LEA DX,REGISTER_SUCCESS
		MOV AH,09H
		INT 21H
		JMP L3
L3:
	GOODS_NAME_INPUT:
		LEA DX,OUTPUT_MSG4
		MOV AH,09H
		INT 21H
		LEA DX,GOODS_NAME;输入商品名称
		MOV AH,0AH
		INT 21H
		
		CMP 2[GOODS_NAME],0DH;键入回车
		JE L1		
		LEA SI,GOODS_NAME+1;商品名字后面的回车（0dh）需要处理为0
		MOV AL,[SI]
		LEA SI,GOODS_NAME+2
		MOV AH,0
		ADD SI,AX
		MOV WORD PTR [SI],0

	FIND_GOODS:
		MOV CH,0;遍历商品
		MOV CL,0;遍历名称
		LOOP3:
			LEA SI,GA1
			MOVSX DX,CH
			IMUL DX,21
			ADD SI,DX
			LEA DI,GOODS_NAME+2
			LOOP4:
				MOV AH,[SI]
				MOV BH,[DI]
				CMP AH,BH
				JNE NEXT_GOODS
				INC SI
				INC DI
				INC CL
				CMP CL,10
				JE SUCCESS
				JMP LOOP4
			NEXT_GOODS:
				CMP CH,30
				JE FAIL
				INC CH
				JMP LOOP3
	SUCCESS:
		LEA DX,OUTPUT_MSG6
		MOV AH,09H
		INT 21H
		CMP AUTH,1
		JE GOODS_DISPLAY_REGISTER
		JMP GOODS_DISPLAY_UNREGISTER
	FAIL:
		LEA DX,OUTPUT_MSG5
		MOV AH,09H
		INT 21H
		JMP GOODS_NAME_INPUT
	GOODS_DISPLAY_REGISTER:
		;商品名字后面加$
		LEA SI,GOODS_NAME+1
		MOV AL,[SI]
		LEA SI,GOODS_NAME+2
		MOV AH,0
		ADD SI,AX
		MOV WORD PTR [SI],'$'
		LEA DX,GOODS_NAME+2;输出名字
		MOV AH,09H
		INT 21H
		LEA SI,GA1;找到当前商品地址存到si里
		MOVSX DX,CH
		IMUL DX,21
		ADD SI,DX
		JMP COMPUTE;计算推荐度
	GOODS_DISPLAY_UNREGISTER:
		;商品名字后面加$
		LEA SI,GOODS_NAME+1
		MOV AL,[SI]
		LEA SI,GOODS_NAME+2
		MOV AH,0
		ADD SI,AX
		MOV WORD PTR [SI],'$'
		LEA DX,GOODS_NAME+2;输出名字
		MOV AH,09H
		INT 21H
		JMP L1;回到功能1
	COMPUTE:
		MOV ECX,0
		MOV CL,[SI+0AH];折扣
		MOV BX,[SI+0DH];销售价
		IMUL CX,BX;CX为折扣乘以销售价
		MOV EAX,0
		MOV EDX,0
		MOV AX,[SI+0BH];进货价
		IMUL EAX,IMUL1;	
		IDIV ECX;此时EAX为结果部分
		MOV ECX,EAX;
		MOV EAX,0
		MOV EBX,0
		MOV EDX,0
		MOV AX,[SI+11H];已售数量
		MOV BX,[SI+0FH];进货数量
		IMUL EAX,IMUL2
		IDIV EBX
		ADD EAX,ECX
		MOV SCORE,EAX
		JMP L4

L4:
	MOV EBX,SCORE
	CMP EBX,100
	JGE A
	CMP EBX,50
	JGE B
	CMP EBX,10
	JGE CC
	JMP F
	
A:
	MOV DL,32;空格
	MOV AH,02H
	INT 21H
	MOV DL,41H
	MOV AH,2
	INT 21H
	MOV DL,0AH;换行
	MOV AH,02H
	INT 21H
	JMP GOODS_NAME_INPUT
B:
	MOV DL,32;空格
	MOV AH,02H
	INT 21H
	MOV DL,42H
	MOV AH,2
	INT 21H
	MOV DL,0AH;换行
	MOV AH,02H
	INT 21H
	JMP GOODS_NAME_INPUT
CC:
	MOV DL,32;空格
	MOV AH,02H
	INT 21H
	MOV DL,43H
	MOV AH,2
	INT 21H
	MOV DL,0AH;换行
	MOV AH,02H
	INT 21H
	JMP GOODS_NAME_INPUT
F:
	MOV DL,32;空格
	MOV AH,02H
	INT 21H
	MOV DL,46H
	MOV AH,2
	INT 21H
	MOV DL,0AH;换行
	MOV AH,02H
	INT 21H
	JMP GOODS_NAME_INPUT

INDEX1:
	MOV DL,0AH;换行
	MOV AH,02H
	INT 21H
	MOV AUTH,0
	JMP L3
EXIT:
	MOV AH,4CH
	INT 21H
ERROR_NAME:
	LEA DX,ERROR_MSG_N
	MOV AH,9
	INT 21H
	JMP L1
ERROR_PWD:
	LEA DX,ERROR_MSG_P
	MOV AH,9
	INT 21H
	JMP L1
CODE ENDS
END START